### ISSUE TITLE
Fehlerbehandlung bei unerwarteten Feldern

### ISSUE THREAD

**Issue by seb-bau** [seb-bau/wowicache#2]
full_message
    Traceback (most recent call last):

      File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
        return _run_code(code, main_globals, None,

      File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
        exec(code, run_globals)

      File "/var/projects/wowicache/venv/lib/python3.10/site-packages/wowicache/update_cache.py", line 401, in <module>
        cache_to_db(sys.argv[1])

      File "/var/projects/wowicache/venv/lib/python3.10/site-packages/wowicache/update_cache.py", line 246, in cache_to_db
        persons = wowicon.get_persons(fetch_all=True)

      File "/var/projects/wowicache/venv/lib/python3.10/site-packages/wowipy/wowipy.py", line 1102, in get_persons
        ret_per = Person(**data)

      File "/var/projects/wowicache/venv/lib/python3.10/site-packages/wowipy/models.py", line 906, in __init__
        self.natural_person = NaturalPerson(**natural_person)

    TypeError: NaturalPerson.__init__() got an unexpected keyword argument 'title'

**Comment by seb-bau** [comment]
Ist ein issue für WowiPy
